cybergizer-hq/retrospective

app/javascript/components/ActionItem/ActionItemBody/index.js
app/javascript/components/Card/CardBody/index.js
app/javascript/components/Card/Likes/index.js
app/javascript/components/Card/index.js
app/javascript/packs/ready_button_component.jsx
app/views/boards/show.html.erb
app/views/cards/_form.html.erb
docker-compose.yml
package.json

- Improve react components code
- Fix warnings in console
- Lint

Fix port conflict, improve code of ReadyButton

---

config/environments/production.rb

https://github.com/cybergizer-hq/retrospective/issues/63

set up force_ssl

---

app/javascript/components/InviteBlock/index.js
app/queries/boards/suggestions.rb

https://github.com/cybergizer-hq/retrospective/issues/70

Add conditions for autocomplete

---

app/javascript/components/ActionItem/ActionItemBody/index.js
app/javascript/components/ActionItemColumn/index.js
app/javascript/components/CardColumn/Card/CardFooter/CardFooter.css
app/javascript/components/CardColumn/Card/CardFooter/index.js
app/javascript/components/CardColumn/Card/CommentsDropdown/index.js
app/javascript/components/CardColumn/Card/card-popup/card-popup.css
app/javascript/components/CardColumn/Card/card-popup/card-popup.jsx
app/javascript/components/CardColumn/Card/index.js
app/javascript/components/CardColumn/index.js
app/javascript/components/PrevActionItemColumn/index.js
app/javascript/fragments/user.graphql
package.json

done:
1. make changes to remove mistake caused by backend updates with user nickname
2. add popup component with card, opening by comment button
3. popup now can be closed by click on the background
should do:
1. delete comments
2. update popup view
3 add button for closing popup

82 make a pop up to read/write comments

---

app/javascript/components/ActionItem/ActionItemBody/index.js
app/javascript/components/ActionItemColumn/index.js

https://github.com/cybergizer-hq/retrospective/issues/90

90 add the same functionality for hotkeys  for Action Items (as in cards)

---

app/controllers/boards_controller.rb
db/seeds.rb

81 order cards by desc

---

app/controllers/boards_controller.rb
app/graphql/types/user_type.rb
app/javascript/components/ActionItem/ActionItemFooter/index.js
app/javascript/components/ActionItem/index.js
app/javascript/components/ActionItemColumn/index.js
app/javascript/components/CardColumn/Card/Card.css
app/javascript/components/CardColumn/Card/CardFooter/index.js
app/javascript/components/CardColumn/Card/card-popup/card-popup.jsx
app/javascript/components/CardColumn/Card/card-user/card-user.jsx
app/javascript/components/CardColumn/Card/index.js
app/javascript/components/CardColumn/index.js
app/javascript/components/PrevActionItemColumn/index.js
app/javascript/fragments/user.graphql
app/javascript/utils/helpers.js
docker-compose.yml

https://github.com/cybergizer-hq/retrospective/pull/new/user_without_avatar_has_initials_avatar

make user component of card & user avatar of initials

---

app/views/action_items/index.html.erb

101 changing board names on assigned action items page

---

app/models/board.rb
app/models/membership.rb
app/operations/boards/continue.rb
app/policies/action_item_policy.rb
app/policies/board_policy.rb
app/policies/card_policy.rb
app/policies/comment_policy.rb
spec/models/board_spec.rb
spec/operations/continue_spec.rb
spec/policies/action_item_policy_spec.rb
spec/policies/board_policy_spec.rb

96 add roles policies

---

app/assets/stylesheets/board.scss
app/javascript/components/User/index.js
app/javascript/components/User/style.css

https://github.com/cybergizer-hq/retrospective/issues/94

add-tooltip-to-user-avatar

---

app/javascript/components/ActionItemColumn/action-item-column-header/action-item-column-header.jsx
app/javascript/components/ActionItemColumn/index.js
app/javascript/components/CardColumn/Card/card-popup/card-popup.css
app/javascript/components/CardColumn/card-column-header/card-column-header.jsx
app/javascript/components/CardColumn/index.js
app/javascript/components/card-table.jsx
app/javascript/mocks/all-mocks.js
app/views/boards/show.html.erb
package.json
yarn.lock

https://github.com/cybergizer-hq/retrospective/issues/87

Fix autofocus bugs

---

app/assets/stylesheets/board.scss

fix for https://github.com/cybergizer-hq/retrospective/pull/109

Add forgotten styles

---

app/controllers/boards_controller.rb

117 only boards (that can be continued) on the pages of "my boards" and "boards where I am"

---

app/javascript/components/ActionItemColumn/index.js
app/javascript/components/CardColumn/Card/CardBody/index.js
app/javascript/components/CardColumn/Card/card-popup/card-popup.jsx
app/javascript/components/CardColumn/Card/card-user-avatar/card-user-avatar.jsx
app/javascript/components/CardColumn/Card/card-user/card-user.jsx
app/javascript/components/CardColumn/Card/index.js
app/javascript/components/CardColumn/card-column-header/card-column-header.jsx
app/javascript/components/CardColumn/index.js
app/javascript/components/CardColumn/operations.gql
app/javascript/components/card-table.jsx
app/javascript/components/new-card-body/new-card-body.jsx
app/javascript/components/new-card-body/operations.gql
package.json
yarn.lock

Close https://github.com/cybergizer-hq/retrospective/issues/88

firstly add card to frontend

---

README.md

Edited readme with instructions on how to launch the project.

steps to bring project alive

---

app/operations/boards/continue.rb
app/views/boards/_board_card.html.erb
spec/operations/continue_spec.rb

Adding board title borrowed from previous board

---

app/javascript/components/ActionItem/index.js
app/javascript/components/ActionItemColumn/index.js
app/javascript/components/CardColumn/Card/CardBody/index.js
app/javascript/components/CardColumn/Card/index.js
app/javascript/components/CardColumn/index.js
app/javascript/components/PrevActionItemColumn/index.js
app/javascript/components/card-table.jsx

This task is related to https://github.com/cybergizer-hq/retrospective/pull/180

add opportunity to delete any cards if you are the cretor of board

---

app/helpers/authorization_helper.rb
app/views/home/index.html.erb

- Link for auth logins rendered if ENV variables are set

auth links rendering dependent on ENV variables present

---

app/javascript/components/CardColumn/Card/CommentsDropdown/index.js
app/javascript/components/CardColumn/Card/card-popup/card-popup.css
app/javascript/components/CardColumn/Card/card-popup/card-popup.jsx

Closes https://github.com/cybergizer-hq/retrospective/issues/113

add focus and hotkeys

---

app/javascript/components/invite-block/invite-block.jsx

 fixed view options when clearing input

---

app/controllers/action_items_controller.rb
app/views/action_items/index.html.erb

220 assigned tasks page improvements

---

app/graphql/mutations/add_action_item_mutation.rb
app/graphql/types/action_item_type.rb
app/models/action_item.rb
db/migrate/20201223171129_add_author_ref_to_action_items.rb
db/schema.rb
db/seeds.rb
spec/controllers/action_items_controller_spec.rb
spec/factories/action_item_factory.rb
spec/graphql/mutations/action_items/add_action_item_spec.rb

227 add author to action items

---

.dockerdev/Dockerfile
.github/workflows/aws.yml

Our Deploy to Amazon has broken. Fixed the command to run the build and the path to AptFile in Dockerfile

Deploy on Amazon ECS

---

.dockerdev/Dockerfile

Add yarn setup in dockerfile to install dependencies when build to run webpacker

Add install yarn

---

app/models/board.rb

Fix destroy boards bug

---

Dockerfile

install gems before copy a project to use cache on this step

Improve Dockerfile:

---

app/models/user.rb
db/migrate/20210805084439_change_null_to_user_nickname.rb
db/schema.rb
lib/tasks/update_nickname.rake

Set nickname

---

.github/workflows/aws.yml

Bump bundler version for AWS builds.
https://github.com/cybergizer-hq/retrospective/blob/6e3068e587ad19a6a12620393b3edee21c5a345d/docker-compose.yml#L13

Bump bundler for AWS build

---

app/graphql/mutations/like_card_mutation.rb
app/javascript/components/comment/comment.jsx
app/javascript/components/comment/style.module.less
app/models/permission.rb
app/operations/boards/cards/build_permissions.rb
app/operations/boards/cards/comments/build_permissions.rb
app/policies/card_policy.rb
app/policies/comment_policy.rb
db/migrate/20210802084413_add_like_comment_permission.rb
db/seeds.rb
spec/api/v1/comments_spec.rb
spec/graphql/mutations/comments/like_comment_spec.rb
spec/operations/boards/cards/comments/comments_build_permissions_spec.rb
spec/policies/card_policy_spec.rb
spec/policies/comment_policy_spec.rb

Add like comment permission

---

app/serializers/card_serializer.rb

Sort comments by created_at in ascending order

---

app/graphql/types/action_item_type.rb
app/javascript/components/action-item-edit/action-item-edit.jsx
app/javascript/components/action-item/action-item.jsx
app/javascript/components/card-user/card-user.jsx
app/javascript/components/new-action-item/new-action-item.jsx
app/javascript/components/ready-button-container.jsx
app/javascript/components/ready-button/ready-button.jsx
app/javascript/fragments/action_item.graphql
app/views/boards/show.html.erb
config/application.rb
spec/graphql/mutations/action_items/add_action_item_spec.rb

Camelize props

---

app/controllers/api/v1/boards_controller.rb
app/controllers/boards_controller.rb
config/routes.rb
spec/api/v1/boards_spec.rb

Add API::V1::BoardsController#update action to REST API to use it a new react component

Add route api/v1/boards#update

---

app/controllers/api/v1/boards_controller.rb
app/javascript/components/api/boards-api.js
app/models/board.rb
app/serializers/board_serializer.rb
config/routes.rb
spec/api/v1/boards_spec.rb
spec/models/board_spec.rb
spec/serializers/board_serializer_spec.rb

- action #my returns list of boards that user's a creator
- action #participating returns list of boards that user's a member
- boards're grouped by a history flow
- return users count and 4 users for representing

Update Boards API

---

app/controllers/api/v1/action_items_controller.rb
app/serializers/action_item_serializer.rb
config/routes.rb
spec/api/v1/action_items_spec.rb
spec/factories/action_item_factory.rb

- Add `#index` to  `API::V1::ActionItemsController`
- Refactor code

Add missed actions to API::V1::ActionItemsController

---

app/javascript/components/action-item-column/action-item-column.jsx
app/javascript/components/action-item/action-item.jsx
app/javascript/components/card-footer/card-footer.jsx
app/javascript/components/card-table.jsx
app/javascript/components/card/card.jsx
app/javascript/components/comments-dropdown/comments-dropdown.jsx
app/javascript/components/likes/likes.jsx
app/javascript/components/new-card-body/new-card-body.jsx
app/views/boards/show.html.erb

Fix 500 error when user is unauthorized
